name: Deploy PR previews

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          pages-base-url: www.pinnaclesmp.org
          wait-for-pages-deployment: true
          comment: true
          qr-code: true
